export const api_root = "http://127.0.0.1:5005";

export const unit1_check_arr = [
  "brk1",
  "brk2",
  "bus",
  "category",
  "comps",
  "control",
  "cpt1",
  "cpt2",
  "cpt3",
  "ct1",
  "ct2",
  "ct3",
  "ct4",
  "ct5",
  "ct6",
  "ct7",
  "ct8",
  "ct9",
  "ct10",
  "ct11",
  "ct12",
  "ctrl1",
  "ctrl2",
  "ft1",
  "ft2",
  "gct1",
  "gct2",
  "grstud1",
  "grstud2",
  "irview1",
  "irview2",
  "irview3",
  "irview4",
  "metal1",
  "misc",
  "pt1",
  "pt2",
  "pt3",
  "pt4",
  "sa1",
  "sa2",
  "unit1_labor",
  "unit1_mfg",
  "view1",
  "view2",
  "view3",
  "view4",
];

export const unit1_features = [
  "brk1_id",
  "brk2_id",
  "brk1_designation",
  "brk2_designation",
  "bus_id",
  "category_id",
  "comps_id",
  "control_id",
  "ctrl1_id",
  "ctrl2_id",
  "cpt1_id",
  "cpt2_id",
  "cpt3_id",
  "cpt1_connection",
  "cpt2_connection",
  "cpt3_connection",
  "ct1_id",
  "ct2_id",
  "ct3_id",
  "ct4_id",
  "ct5_id",
  "ct6_id",
  "ct7_id",
  "ct8_id",
  "ct9_id",
  "ct10_id",
  "ct11_id",
  "ct12_id",
  "ctrl1_id",
  "ft1_id",
  "ft2_id",
  "gct1_id",
  "gct2_id",
  "grstud1_id",
  "grstud2_id",
  "irview1_id",
  "irview2_id",
  "irview3_id",
  "irview4_id",
  "metal1_id",
  "misc_id",
  "pt1_id",
  "pt2_id",
  "pt3_id",
  "pt4_id",
  "pt1_con",
  "pt2_con",
  "pt3_con",
  "pt4_con",
  "sa1_id",
  "sa2_id",
  "unit1_note",
  "unit1_labor",
  "unit1_mfg",
  "view1_id",
  "view2_id",
  "view3_id",
  "view4_id",
];

export const unit1_features_essential = [
  "brk1_id",
  "brk2_id",
  "brk1_designation",
  "brk2_designation",
  "bus_id",
  "comps_id",
  "cpt1_id",
  "cpt2_id",
  "cpt3_id",
  "pt1_id",
  "pt2_id",
  "pt3_id",
  "pt4_id",
];

export const unit1_optional_features = [
  "brk1",
  "brk2",
  "control",
  "ct1",
  "ct2",
  "ct3",
  "ct4",
  "ct5",
  "ct6",
  "ct7",
  "ct8",
  "ct9",
  "ct10",
  "ct11",
  "ct12",
  "cpt1",
  "cpt2",
  "cpt3",
  "cptfuse1",
  "cptfuse2",
  "cptfuse3",
  // "ctrl1",
  // "ctrl2",
  "gct1",
  "gct2",
  // "ft1",
  // "ft2",
  "grstud1",
  "grstud2",
  "irview1",
  "irview2",
  "irview3",
  "pt1",
  "pt2",
  "pt3",
  "pt4",
  "ptfuse1",
  "ptfuse2",
  "ptfuse3",
  "ptfuse4",
  "sa1",
  "sa2",
  "view1",
  "view2",
  "view3",
  "view4",
];

export const unit1_optional_features_obj = {
  control: "Controls",
  brk1:"Breaker Kit - Lower Compartment",
  brk2:"Breaker Kit - Upper Compartment",
  ct1: "Current Transformer Meetering - Lower Breaker Lower Side",
  ct2: "Current Transformer Meetering - Lower Breaker Lower Side",
  ct3: "Current Transformer Protective - Lower Breaker Lower Side",
  ct4: "Current Transformer Meetering - Lower Breaker Upper Side",
  ct5: "Current Transformer Meetering - Lower Breaker Upper Side",
  ct6: "Current Transformer Protective - Lower Breaker Upper Side",
  ct7: "Current Transformer Meetering - Upper Breaker Lower Side",
  ct8: "Current Transformer Meetering - Upper Breaker Lower Side",
  ct9: "Current Transformer Protective - Upper Breaker Lower Side",
  ct10: "Current Transformer Meetering - Upper Breaker Upper Side",
  ct11: "Current Transformer Meetering - Upper Breaker Upper Side",
  ct12: "Current Transformer Protective - Upper Breaker Upper Side",
  cpt1: "Control Power Transformer - Lower Compartment",
  cpt2: "Control Power Transformer - Upper Compartment",
  cpt3: "Control Power Transformer - Fix Mount, Rear Position",
  cptfuse1: "Fuse for CPT - Lower Position",
  cptfuse2: "Fuse for CPT - Upper Position",
  cptfuse3: "Fuse Truck for CPT - Lower Position",
  // ctrl1: "Control Package for Lower Breaker",
  // ctrl2: "Control Package for Lower Breaker",
  // "ft1",
  // "ft2",
  gct1: "Current Transformer Zero Sequence - Lower Cable Connection",
  gct2: "Current Transformer Zero Sequence - Upper Cable Connection",
  grstud1: "Ground Studs - Lower Cable Connection",
  grstud2: "Ground Studs - Upper Cable Connection",
  irview1: "IR Window, Position 1",
  irview2: "IR Window, Position 2",
  irview3: "IR Window, Position 3",
  pt1: "Voltage Transformer - Lower Comparment",
  pt2: "Voltage Transformer - Mid-Lower Compartment",
  pt3: "Voltage Transformer - Mid-Upper Compartment",
  pt4: "Voltage Transformer - Upper Compartment",
  ptfuse1: "Fuse for Voltage Transformer - Lower Compartment",
  ptfuse2: "Fuse for Voltage Transformer - Mid-Lower Compartment",
  ptfuse3: "Fuse for Voltage Transformer - Mid-Upper Compartment",
  ptfuse4: "Fuse for Voltage Transformer - Upper Compartment",
  sa1: "Surge Arrester - Lower Cable Connection",
  sa2: "Surge Arrester - Upper Cable Connection",
  view1: "Viewing Window, Position 1",
  view2: "Viewing Window, Position 1",
  view3: "Viewing Window, Position 1",
  view4: "Viewing Window, Position 1",
};

export const category = {
  bus_bar_asm: 100,
  bus_bar: 101,
  compartment: 110,
  control: 118,
  current_tranformer: 202,
  voltage_tranformer: 220,
  control_power_transformer: 207,
  enclosure: 234,
  gct: 212,
};
